---
- hosts: localhost
  vars:
    kubectl_ver: v1.24.0
    jq_ver: 1.6
    hashi_apps:
      - name: vault
        ver: 1.9.4
  roles:
    - role: andrewrothstein.bash
    - role: andrewrothstein.hashi
    - role: andrewrothstein.jq
    - role: andrewrothstein.kubectl

